version: '3'
services:
  balance-service:
    build: ./balance-service
    volumes:
      - ./balance-service:/usr/src/app
    ports:
      - "8000:80"

    networks:
      - network

  product-service:
    build: ./product-service
    volumes:
      - ./product-service:/usr/src/app
    ports:
      - "8001:80"

    networks:
      - network

  location-service:
    build: ./location-service
    volumes:
      - ./location-service:/usr/src/app
    ports:
      - "8002:80"

    networks:
      - network

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

    networks:
      - network

  movement-service:
    build: ./movement-service
    volumes:
      - ./movement-service:/usr/src/app
    ports:
      - "8003:80"
    depends_on:
      - rabbitmq

    networks:
      - network

  movement-log-consumer:
    build: ./movement-log-consumer
    depends_on:
      - rabbitmq
    volumes:
      - ./movement-log-consumer:/usr/src/app

    networks:
      - network

networks:
  network: {}